# Generated by Django 4.2.3 on 2023-07-16 14:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_student_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('family_name', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Invalid Email')])),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
