# Generated by Django 4.2.3 on 2023-07-16 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_student_1_delete_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student_1',
            new_name='Student',
        ),
    ]
